server:
  port: 8088

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3307/auth_db
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7d7dc0ea6be0e1f1b4e2e9a1c8
  access-token-expiration: 900000
  refresh-token-expiration: 604800000